backend:
  name: gitlab
  branch: main # Branch to update (optional; defaults to master)
  repo: Porush264/blog
  auth_type: pkce
  app_id: 001e8c5bbcbd77ece4d6957905141455cbe983885cdf618b05118a5e3447e554

media_folder: 'assets/img'
publish_mode: editorial_workflow
site_url: https://porush.pages.dev/

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
